// Nivel3/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivro } from '../src/controle/ControleLivros';
import { ControleEditora } from '../src/controle/ControleEditora';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

// const LivroDados = () => {
//   return (
//     <main>
//       <h1>Olá mundo</h1>
//     </main>
//   );
// };

const LivroDados = () => {
  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  const tratarCombo = (evento) => {
    setCodEditora(Number(evento.target.value));
  };

  const incluir = (evento) => {
    evento.preventDefault();

    const novoLivro = {
      codigo: 0,
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora
    };

    controleLivro.incluir(novoLivro);
    navigate('/');
  };

  return (
    <main>
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir} className='form-body'>
        <div>
          <label className='label-class'>Título:</label>
          <input className='form-control'
            type="text"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
            required
          />
        </div>
        <div>
          <label className='label-class'>Resumo:</label>
          <textarea className='form-control'
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
            required
          />
        </div>
        <div>
          <label>Editora:</label>
          <select value={codEditora} onChange={tratarCombo} className='form-control'>
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className='label-class'>Autores (1 por linha):</label>
          <textarea className='form-control'
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
            required
          />
        </div>
        <button type="submit" className='btn btn-primary'>Salvar Dados</button>
      </form>
    </main>
  );
};

export default LivroDados;

// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {

  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;
  private router: Router;

  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService,
    router: Router
  ) {
    this.livro = new Livro(0, 0, '', '', []);
    this.servEditora = servEditora;
    this.servLivros = servLivros;
    this.router = router;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n'); 
    this.servLivros.incluir(this.livro); 
    this.router.navigateByUrl('/lista');
  };
}

<div class="container">
    <h2>Dados do Livro</h2>
    <form (ngSubmit)="incluir()">
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" id="titulo" [(ngModel)]="livro.titulo" name="titulo" class="form-control" required>
      </div>
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea id="resumo" [(ngModel)]="livro.resumo" name="resumo" class="form-control" required></textarea>
      </div>
      <div class="form-group">
        <label for="codEditora">Editora</label>
        <select id="codEditora" [(ngModel)]="livro.codEditora" name="codEditora" class="form-control" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores (1 por linha)</label>
        <textarea id="autores" [(ngModel)]="autoresForm" name="autores" class="form-control"></textarea>
      </div>
      <br>
      <button type="submit" class="btn btn-primary">Incluir Livro</button>
    </form>
  </div>
