// Segundo semestre/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {

  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir = (codigo: number): void => {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container my-4">
    <h1 class="list-title">Catálogo de Livros</h1>
  
    <table class="table table-striped">
      <thead class="table-header">
        <tr>
          <th scope="col">Código</th>
          <th scope="col">Título</th>
          <th scope="col">Editora</th>
          <th scope="col">Resumo</th>
          <th scope="col">Autores</th>
        </tr>
      </thead>
      <tbody class="table-body">
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
  
          <td>
            {{ livro.titulo }}
            <br>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">
              Excluir
            </button>
          </td>
  
          <td>{{ obterNome(livro.codEditora) }}</td>
  
          <td>{{ livro.resumo }}</td>
  
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>

// Nivel3/livros-react/src/LivroLista.js
import React, { useEffect, useState } from 'react';
import { ControleLivro } from '../src/controle/ControleLivros';
import { ControleEditora } from '../src/controle/ControleEditora';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro = (props) => {
  const { livro, excluir } = props;

  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  return (
    <tr>
      <td>
        {livro.titulo}
        <br></br>
        <button onClick={() => excluir(livro.codigo)} className='btn btn-danger'>Excluir</button>
      </td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    if (!carregado) {
      const livrosObtidos = controleLivro.obterLivros();
      setLivros(livrosObtidos);
      setCarregado(true);
    }
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivro.excluir(codigo);
    setCarregado(false);
  };

  return (
    <main>
      <h1 className='list-title'>Catálogo de Livros</h1>
      <table className='table'>
        <thead className='table-header'>
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody className='table-body'>
          {livros.map((livro) => (
            <LinhaLivro
              key={livro.codigo}
              livro={livro}
              excluir={excluir}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;
